# Generated by Django 3.0.6 on 2020-08-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
